name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch or tag to publish (manual run)"
        required: true
  pull_request:
  push:

jobs:
  build_wheels_windows:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        llvm-version: ['18', '19', '20', '21', '22']
        exclude:
          - os: macos-latest
            llvm-version: '22'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install LLVM (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ matrix.llvm-version }}
          sudo apt-get install -y clang-${{ matrix.llvm-version }}
          echo "CC=clang-${{ matrix.llvm-version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.llvm-version }}" >> $GITHUB_ENV
      - name: Install LLVM (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm@${{ matrix.llvm-version }}
          echo "LLVM_DIR=$(brew --prefix llvm@${{ matrix.llvm-version }})" >> $GITHUB_ENV
          echo "CC=$(brew --prefix llvm@${{ matrix.llvm-version }})/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@${{ matrix.llvm-version }})/bin/clang++" >> $GITHUB_ENV

      - name: Collect liborc_rt
        run: |
          echo $($CC -print-runtime-dir)
          ls $($CC -print-runtime-dir)
          mkdir ${{ matrix.os }}-${{ matrix.llvm-version }}
          cp $($CC -print-runtime-dir)/liborc-rt*.a ./${{ matrix.os }}-${{ matrix.llvm-version }}/
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.llvm-version }}
          path: ./${{ matrix.os }}-${{ matrix.llvm-version }}